name: Build and push Docker image on code change

on:
  push:
    branches:
      - '*' # 监听所有分支上的代码变更

jobs:
  build_and_push:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: docker.io/lupus721/jsoncrack
          flavor: |
            latest=true
          tags: |
            type=sha,format=short
            type=raw,enable=true,priority=100
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=match,regex=^(v\d+\.\d+\.?\d*)$,group=1,priority=200
            type=match,regex=^v(\d+)$,group=1,priority=190
            type=branch,enable=true,priority=180
            type=schedule,enable=true,priority=170,cron=* * * * *
            type=ref,event=pr,prefix=pr-,enable=true,priority=160

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # 如果需要添加 attest-build-provenance 或其他后续步骤，请在此处添加
